export const POPULAR_CONDOS = [
  {
    id: 1,
    name: "Kave Town Space",
    nameEn: "Kave Town Space",
    location: "ติดถนนพหลโยธิน ต.คลองหนึ่ง อ.คลองหลวง จ.ปทุมธานี",
    locationShort: "ถนนพหลโยธิน",
    price: "13,000 - 24,000",
    priceUnit: "บาท/เดือน",
    image: "/images/kave.jpg",
    galleryImages: [
      "/images/kave.jpg",
      "/modern-condo-living-room.jpg",
      "/condo-bedroom.jpg",
      "/condo-kitchen.jpg",
      "/condo-bathroom.jpg",
    ],
    description:
      "คอนโดที่เน้นไลฟ์สไตล์คนรุ่นใหม่ (Gen Z) ดีไซน์ทันสมัย และมีพื้นที่ส่วนกลางเยอะมาก ติดม.กรุงเทพรังสิตเพียง ~200 เมตร เดินถึงได้สบายมาก",
    phone: "0644456789",
    nearbyUniversities: [
      { name: "ม.กรุงเทพ (รังสิต)", distance: "~200 เมตร" },
      { name: "ม.ธรรมศาสตร์ (รังสิต)", distance: "~5 กม." },
    ],
    transit: [{ name: "SRT สายสีแดง (สถานีรังสิต)", distance: "~6-7 กม." }],
    nearbyPlaces: ["Imagine Village (คอมมูนิตี้มอลล์)", "ฟิวเจอร์พาร์ค รังสิต (~6.5 กม.)", "โรงพยาบาลภัทร-ธนบุรี"],
    facilities: ["สระว่ายน้ำ (Sky Pool)", "Kave Club", "Co-Working Space", "Theater Room", "ฟิตเนส", "ห้องสมุด", "สวนลอยฟ้า"],
  },
  {
    id: 2,
    name: "Plum Condo Park Rangsit",
    nameEn: "Plum Condo Park Rangsit",
    location: "ถนนพหลโยธิน ต.คลองหนึ่ง อ.คลองหลวง จ.ปทุมธานี",
    locationShort: "ถนนพหลโยธิน",
    price: "10,000 - 23,000",
    priceUnit: "บาท/เดือน",
    image: "/images/plum.jpg",
    galleryImages: [
      "/images/plum.jpg",
      "/resort-style-condo.jpg",
      "/condo-bedroom.jpg",
      "/condo-pool.jpg",
      "/condo-lounge.jpg",
    ],
    description: "คอนโดสไตล์รีสอร์ท พื้นที่โครงการขนาดใหญ่ เน้นความร่มรื่นและส่วนกลางที่กว้างขวาง มีสระว่ายน้ำขนาดใหญ่และลู่วิ่งจอกกิ้ง",
    phone: "0256789012",
    nearbyUniversities: [
      { name: "ม.กรุงเทพ (รังสิต)", distance: "~750 เมตร" },
      { name: "ม.ธรรมศาสตร์ (รังสิต)", distance: "~4 กม." },
    ],
    transit: [{ name: "SRT สายสีแดง (สถานีรังสิต)", distance: "~5.5 กม." }],
    nearbyPlaces: ["บุญถาวร รังสิต", "Tesco Lotus รังสิต", "ตลาดไท (~4.5 กม.)"],
    facilities: ["สระว่ายน้ำขนาดใหญ่ 2 สระ", "สนามแบดมินตัน", "ห้องอ่านหนังสือ", "ฟิตเนส", "สวนขนาดใหญ่", "ลู่วิ่งจอกกิ้ง"],
  },
  {
    id: 3,
    name: "BE Condo Phahon Yothin",
    nameEn: "BE Condo Phahon Yothin",
    location: "ถนนพหลโยธิน ต.คลองหนึ่ง อ.คลองหลวง จ.ปทุมธานี",
    locationShort: "ถนนพหลโยธิน",
    price: "14,000 - 20,000",
    priceUnit: "บาท/เดือน",
    image: "/images/be.jpeg",
    galleryImages: [
      "/images/be.jpeg",
      "/modern-living-room.jpg",
      "/bedroom-with-balcony.jpg",
      "/kitchen-area.jpg",
      "/modern-bathroom.png",
    ],
    description:
      "คอนโดที่เน้นความเป็นส่วนตัว ทันสมัย และเดินทางสะดวกติดถนนใหญ่ ใกล้ม.กรุงเทพ ติดฝั่งตรงข้ามหรือเยื้องเล็กน้อย ต้องข้ามสะพานลอย",
    phone: "0287654321",
    nearbyUniversities: [
      { name: "ม.กรุงเทพ (รังสิต)", distance: "~1-2 กม." },
      { name: "ม.ธรรมศาสตร์ (รังสิต)", distance: "~3.5 กม." },
    ],
    transit: [{ name: "SRT สายสีแดง (สถานีรังสิต)", distance: "~5-6 กม." }],
    nearbyPlaces: ["โฮมโปร รังสิต", "ฟิวเจอร์พาร์ค รังสิต", "นิคมอุตสาหกรรมนวนคร"],
    facilities: ["สระว่ายน้ำ", "ฟิตเนส", "ห้องซาวน่า", "ห้องประชุม", "ระบบรักษาความปลอดภัย 24 ชม."],
  },
  {
    id: 4,
    name: "Attitude BU",
    nameEn: "Attitude BU",
    location: "ถนนพหลโยธิน ต.คลองหนึ่ง อ.คลองหลวง จ.ปทุมธานี",
    locationShort: "ถนนพหลโยธิน",
    price: "11,000 - 17,000",
    priceUnit: "บาท/เดือน",
    image: "/images/attittude.webp",
    galleryImages: [
      "/images/attittude.webp",
      "/creative-space.jpg",
      "/bedroom-modern.jpg",
      "/kitchen-modern.jpg",
      "/lounge-area.jpg",
    ],
    description:
      "คอนโดดีไซน์โดดเด่นเอาใจเด็กแนว (Creative Space) เน้นสีสันและความสนุกสนานในการอยู่อาศัย ฝั่งตรงข้าม ม.กรุงเทพ ระยะทางประมาณ 200-300 เมตร",
    phone: "0298765432",
    nearbyUniversities: [
      { name: "ม.กรุงเทพ (รังสิต)", distance: "~200-300 เมตร" },
      { name: "ม.ธรรมศาสตร์ (รังสิต)", distance: "~4 กม." },
    ],
    transit: [{ name: "SRT สายสีแดง (สถานีรังสิต)", distance: "~6 กม." }],
    nearbyPlaces: ["Mega Home", "Tesco Lotus", "ตลาดบางขัน"],
    facilities: ["Sky Lounge", "สระว่ายน้ำดาดฟ้า", "Co-Working Space", "Creative Space", "โซนดนตรี", "คาเฟ่", "ฟิตเนส"],
  },
]

export const DAILY_APARTMENTS = [
  {
    id: 101,
    name: "บ้านเมฆหมอก Service Apartment",
    location: "Sukhumvit 64",
    locationFull: "ซอยสุขุมวิท 64 (พญาไท)",
    priceMonth: "6,000 - 6,500",
    priceDay: "650",
    image:
      "/images/e0-b8-9a-e0-b9-89-e0-b8-b2-e0-b8-99-e0-b9-80-e0-b8-a1-e0-b8-86-e0-b8-ab-e0-b8-a1-e0-b8-ad-e0-b8-81-20service-20apartment.webp",
    galleryImages: [
      "/images/e0-b8-9a-e0-b9-89-e0-b8-b2-e0-b8-99-e0-b9-80-e0-b8-a1-e0-b8-86-e0-b8-ab-e0-b8-a1-e0-b8-ad-e0-b8-81-20service-20apartment.webp",
      "/service-apartment.jpg",
      "/apartment-living.jpg",
      "/modern-kitchen.jpg",
      "/modern-bathroom.png",
    ],
    description:
      "ชุดสัมมนา บ้านเมฆหมอก Service Apartment มีวิวมองเห็น BTS สยามสเปเซ สูบรรณ์ 64 โครงการห้องพักให้เช่ามีอเมนิตี้ครบครัน ห้องขนาดต่าง ๆ ตั้งแต่ 1-2 ห้อง เข้าออกทางสุขุมวิท 64 ทำให้เดินทางสะดวก ห้องพักสะอาด และปลอดภัย",
    phone: "0274127241-2",
    nearbyUniversities: [{ name: "สถานีรถไฟฟ้า BTS สยาม", distance: "ใกล้เคียง" }],
    transit: [{ name: "BTS สยามสแควร์", distance: "~350 เมตร" }],
    nearbyPlaces: ["สยามสแควร์", "เซ็นทรัลเวิลด์", "สุขุมวิท 64"],
    facilities: [
      "เครื่องปรับอากาศ",
      "เฟอร์นิเจอร์ครบ-ดี เบดดิ้ง",
      "เครื่องในห้องน้ำครบ",
      "โทรทัศน์",
      "ตู้เย็น",
      "ไมโครเวฟ (WIFI) ในห้อง",
      "เครื่องซักผ้า",
    ],
  },
  {
    id: 102,
    name: "ดีดี อพาร์ทเม้นท์",
    location: "Ramkhamhaeng 85",
    locationFull: "ถนนรามคำแหง 85 (บดินทร์บางขัน)",
    priceMonth: "3,500",
    priceDay: "400 - 480",
    image:
      "/images/e0-b8-94-e0-b8-b5-e0-b8-94-e0-b8-b5-20-e0-b8-ad-e0-b8-9e-e0-b8-b2-e0-b8-a3-e0-b9-8c-e0-b8-97-e0-b9-80-e0-b8-a1-e0-b9-89-e0-b8-99-e0-b8-97-e0-b9-8c.webp",
    galleryImages: [
      "/images/e0-b8-94-e0-b8-b5-e0-b8-94-e0-b8-b5-20-e0-b8-ad-e0-b8-9e-e0-b8-b2-e0-b8-a3-e0-b9-8c-e0-b8-97-e0-b9-80-e0-b8-a1-e0-b9-89-e0-b8-99-e0-b8-97-e0-b9-8c.webp",
      "/placeholder.svg?height=400&width=600",
      "/placeholder.svg?height=400&width=600",
      "/placeholder.svg?height=400&width=600",
      "/placeholder.svg?height=400&width=600",
    ],
    description:
      "ดีดี อพาร์ทเม้นท์ มีห้องพักราคาถูกที่สำคัญที่สุด ใกล้หลาย ๆ วิทยาลัย เช่น โรงแรมของราคา และเครื่องสุดท้ายห้อง ห้องขนาด 15 ตร.ม. 18 ตร.ม. ห้องสำหรับนักเรียน และห้องคู่ ครอบครัว",
    phone: "0273322895",
    nearbyUniversities: [{ name: "บดินทร์ (บางขัน)", distance: "ใกล้เคียง" }],
    transit: [{ name: "MRT สถานีบางขัน", distance: "~720 เมตร" }],
    nearbyPlaces: ["สถานีรถไฟฟ้า BTS", "ตลาดขัน", "ห้างสรรพสินค้า"],
    facilities: [
      "เครื่องปรับอากาศ",
      "เฟอร์นิเจอร์ครบ-ดี เบดดิ้ง",
      "เครื่องในห้องน้ำครบ",
      "โทรทัศน์",
      "ตู้เย็น",
      "ไมโครเวฟ (WIFI) ในห้อง",
      "เครื่องซักผ้า",
    ],
  },
  {
    id: 103,
    name: "มีนเรสสิเดนซ์",
    location: "Min Buri",
    locationFull: "มีนบุรี",
    priceMonth: "4,100 - 10,900",
    priceDay: "800",
    image:
      "/images/e0-b8-a1-e0-b8-b5-e0-b8-99-e0-b9-80-e0-b8-a3-e0-b8-aa-e0-b8-aa-e0-b8-b4-e0-b9-80-e0-b8-94-e0-b8-99-e0-b8-8b-e0-b9-8c.webp",
    galleryImages: [
      "/images/e0-b8-a1-e0-b8-b5-e0-b8-99-e0-b9-80-e0-b8-a3-e0-b8-aa-e0-b8-aa-e0-b8-b4-e0-b9-80-e0-b8-94-e0-b8-99-e0-b8-8b-e0-b9-8c.webp",
      "/placeholder.svg?height=400&width=600",
      "/placeholder.svg?height=400&width=600",
      "/placeholder.svg?height=400&width=600",
      "/placeholder.svg?height=400&width=600",
    ],
    description:
      "เมืองเรสสิเดนซ์ เป็นอพาร์ทเมนต์ที่อยู่ตรงกลาง ซอยเมืองแหนม ห้องที่นี่มีฟังก์ชันการทำงานของมี 24 ชั่วโมง เมือง อาหารพร้อมใช้ห้องพักของเหมาะและครบครัน",
    phone: "0273322895",
    nearbyUniversities: [{ name: "มีนบุรี", distance: "ใกล้เคียง" }],
    transit: [{ name: "MRT สถานีบางขัน", distance: "~720 เมตร" }],
    nearbyPlaces: ["ตลาดมีนบุรี", "วัตถุ", "สถานีรถไฟฟ้า"],
    facilities: [
      "เครื่องปรับอากาศ",
      "เฟอร์นิเจอร์ครบ-ดี เบดดิ้ง",
      "เครื่องในห้องน้ำครบ",
      "โทรทัศน์",
      "ตู้เย็น",
      "ไมโครเวฟ (WIFI) ในห้อง",
      "เครื่องซักผ้า",
    ],
  },
  {
    id: 104,
    name: "THE PEAK",
    location: "Khlong Luang",
    locationFull: "คลองหลวง",
    priceMonth: "4,500",
    priceDay: "800",
    image: "/images/the-20peak.webp",
    galleryImages: [
      "/images/the-20peak.webp",
      "/placeholder.svg?height=400&width=600",
      "/placeholder.svg?height=400&width=600",
      "/placeholder.svg?height=400&width=600",
      "/placeholder.svg?height=400&width=600",
    ],
    description:
      "สิ่งมีค่าสำหรับภาษีคุณอังคู่บริหารบ้านเมฆหมอก Service Apartment เชียงมูลไทยซึ่งมาจากภูมิภาคการออกแบบและเผ่าสถาปัตยกรรม ดีไซน์โครงสร้างของอพาร์เมนต์ สภาพแวดล้อมสวยงาม",
    phone: "0644456123",
    nearbyUniversities: [{ name: "ม.บูรพา", distance: "~14 กม." }],
    transit: [{ name: "สถานีรถไฟ", distance: "ใกล้เคียง" }],
    nearbyPlaces: ["คลองหลวง", "ธนบุรี", "ม.บูรพา"],
    facilities: [
      "เครื่องปรับอากาศ",
      "เฟอร์นิเจอร์ครบ-ดี เบดดิ้ง",
      "เครื่องในห้องน้ำครบ",
      "โทรทัศน์",
      "ตู้เย็น",
      "ไมโครเวฟ (WIFI) ในห้อง",
      "ที่จอดรถ",
    ],
  },
]
